name: Update submodule

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      magisk_ver: ${{ steps.get_magisk_version.outputs.magisk_ver }}
      magisk_ver_code: ${{ steps.get_magisk_version.outputs.magisk_ver_code }}
    steps:
      - name: 拉取 Magisk-Patch
        uses: actions/checkout@v4.2.2
      - name: 获取 Magisk 版本信息
        id: get_magisk_version
        run: |
          sudo apt-get install -y dos2unix
          unzip ./magisk_patch/magisk.zip util_functions.sh
          MAGISK_VER=$(cat util_functions.sh | dos2unix | sed -n 's/^MAGISK_VER=//p' | head -n 1 | sed "s/'//g")
          MAGISK_VER_CODE=$(cat util_functions.sh | dos2unix | sed -n 's/^MAGISK_VER_CODE=//p' | head -n 1)
          echo "magisk_ver=$MAGISK_VER" >>$GITHUB_OUTPUT
          echo "magisk_ver_code=$MAGISK_VER_CODE" >>$GITHUB_OUTPUT

  lahaina:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - name: 设置 Git 提交账户
        run: |
          git config --global user.email "30484319+zjw2017@users.noreply.github.com"
          git config --global user.name "柚稚的孩纸"
      - name: 拉取 action_build_lahaina_system
        uses: actions/checkout@v4.2.2
        with:
          repository: Human-Machine-Matrix/action_build_lahaina_system
          token: ${{ secrets.GH_TOKEN }}
          path: action_build_lahaina_system
          submodules: recursive
          fetch-depth: 0
      - name: 提交 action_build_lahaina_system
        run: |
          cd action_build_lahaina_system
          git submodule update --remote --merge
          git commit -am "更新 Magisk ${{ needs.get_version.outputs.magisk_ver }} (${{ needs.get_version.outputs.magisk_ver_code }}) " || echo "无需更新 Magisk"
          git push origin main
  
  liuqin:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - name: 设置 Git 提交账户
        run: |
          git config --global user.email "30484319+zjw2017@users.noreply.github.com"
          git config --global user.name "柚稚的孩纸"
      - name: 拉取 action_build_liuqin_system
        uses: actions/checkout@v4.2.2
        with:
          repository: Human-Machine-Matrix/action_build_liuqin_system
          token: ${{ secrets.GH_TOKEN }}
          path: action_build_liuqin_system
          submodules: recursive
          fetch-depth: 0
      - name: 提交 action_build_liuqin_system
        run: |
          cd action_build_liuqin_system
          git submodule update --remote --merge
          git commit -am "更新 Magisk ${{ needs.get_version.outputs.magisk_ver }} (${{ needs.get_version.outputs.magisk_ver_code }}) " || echo "无需更新 Magisk"
          git push origin main

  kalama:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - name: 设置 Git 提交账户
        run: |
          git config --global user.email "30484319+zjw2017@users.noreply.github.com"
          git config --global user.name "柚稚的孩纸"
      - name: 拉取 action_build_kalama_system
        uses: actions/checkout@v4.2.2
        with:
          repository: Human-Machine-Matrix/action_build_kalama_system
          token: ${{ secrets.GH_TOKEN }}
          path: action_build_kalama_system
          submodules: recursive
          fetch-depth: 0
      - name: 提交 action_build_kalama_system
        run: |
          cd action_build_kalama_system
          git submodule update --remote --merge
          git commit -am "更新 Magisk ${{ needs.get_version.outputs.magisk_ver }} (${{ needs.get_version.outputs.magisk_ver_code }}) " || echo "无需更新 Magisk"
          git push origin main

  PayloadToFlash:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - name: 设置 Git 提交账户
        run: |
          git config --global user.email "30484319+zjw2017@users.noreply.github.com"
          git config --global user.name "柚稚的孩纸"
      - name: 拉取 PayloadToFlash
        uses: actions/checkout@v4.2.2
        with:
          repository: Human-Machine-Matrix/PayloadToFlash
          token: ${{ secrets.GH_TOKEN }}
          path: PayloadToFlash
          submodules: recursive
          fetch-depth: 0
      - name: 提交 PayloadToFlash
        run: |
          cd PayloadToFlash
          git submodule update --remote --merge
          git commit -am "更新 Magisk ${{ needs.get_version.outputs.magisk_ver }} (${{ needs.get_version.outputs.magisk_ver_code }}) " || echo "无需更新 Magisk"
          git push origin main
